Prevent IO exceptions
EDCD/EDDI pull request #1831
Opened 2020-06-19 04:32 UTC by Tkael

This PR is designed to prevent issues like:
- https://rollbar.com/EDCD/EDDI/items/17558/
- https://rollbar.com/EDCD/EDDI/items/16979/
- https://rollbar.com/EDCD/EDDI/items/17609/
- https://rollbar.com/EDCD/EDDI/items/17607/
- https://rollbar.com/EDCD/EDDI/items/17583/

It moves file locking from each individual config file into the `Files` class and if an IO exception occurs it waits and retries several times before completely failing.

May resolve #1780.
Replaces #1808.

2020-06-19 06:29 UTC, GioVAX approved these changes

2020-06-20 22:26 UTC, richardbuckle commented on Utilities/Files.cs
>          /// <returns></returns>
returns the contents of the file

2020-06-20 22:28 UTC, richardbuckle commented on Utilities/Files.cs
> +        private const int readIODelayMs = 25;
Ms is technically "megaseconds" in the SI system, because the short names are case-sensitive. Recommend readIODelayMilleSecs and similarly for write.

2020-06-20 22:30 UTC, richardbuckle commented on Utilities/Files.cs
> +                    throw new IOException("IO read failed for " + fileName + ", too many attempts.");
I'm a big fan of `$"blah {variable} blah" for readability.

2020-06-20 22:36 UTC, richardbuckle requested changes
This is good. I can do the fixes myself, no problem.

2020-06-20 22:36 UTC, richardbuckle commented on Utilities/LockManager.cs
> +                new ConcurrentDictionary<string, lobj>();
Move to one line I think.

2020-06-20 23:18 UTC, richardbuckle approved these changes

2020-06-20 23:18 UTC, merged