Update Rollbar (Mk. II)
EDCD/EDDI pull request #1859
Opened 2020-06-27 04:14 UTC by Tkael

- Updates Rollbar package to latest version
- Tells Rollbar not to collect IP addresses
- Moves logging to an async task so that the calling thread can return more rapidly
- Gracefully filters and redacts data objects without resorting to exceptions
- Allows Rollbar to distinguish between reports from standalone app clients vs. from VoiceAttack plugin clients
- Adds a config toggle (in json only, no UI) to allow users to entirely disable telemetry
- Rollbar's anonymous ID is now regenerated on each app run rather than retained between app runs 
- Reduces web traffic when idle
- Adds telemetry data from prior eddi.log entries to provide context for encountered issues
- Removes Rollbar from the Test class entirely

Note: This updates the Rollbar package by two major releases. Do not merge until after EDDI version 3.7 is released.

2020-07-19 17:46 UTC, GioVAX requested changes

2020-07-19 17:46 UTC, GioVAX commented on EDDI/App.xaml.cs
> +        public static void StartRollbar(EDDIConfiguration configuration)
In this function, we are only using DisableTelemetry.
Can we just pass a bool?

2020-07-19 22:20 UTC, Tkael commented on EDDI/App.xaml.cs
> +        public static void StartRollbar(EDDIConfiguration configuration)
Fair. Done.

2020-07-21 07:25 UTC, GioVAX approved these changes

2020-10-30 10:35 UTC, merged