Auto-generate documents for Script Resolver functions
EDCD/EDDI pull request #2025
Opened 2020-11-29 11:59 UTC by Tkael

Resolves #303
- Re-organizes custom script resolver functions into an interface and class structure
- Moves the script resolver itself into a sub-folder
- Generates Help.md and Functions.md automatically from classes during the post-build sequence

2020-12-09 01:32 UTC, Tkael commented on SpeechResponder/ScriptResolverService/ICustomFunction.cs
> +    }
We use the `ResolverInstance` abstract class to implement nesting / recursion.

2020-12-13 20:41 UTC, richardbuckle requested changes
I haven't read every single wrapped functionin detail.

2020-12-13 20:41 UTC, richardbuckle commented on postBuildTests.bat
>    :: Run just our Credentials test
Need to update the comment, or simply remove it as it's not really adding much.

2020-12-13 20:42 UTC, richardbuckle commented
Apart from the stale comment I'm happy.

2020-12-13 20:52 UTC, richardbuckle commented on SpeechResponder/CustomFunctions/BlueprintDetails.cs
> +        public NativeFunction function => new NativeFunction((values) =>
Sorry, a thought just struck me. Isn't this allocating a new instance of the NativeFunction every time the property is accessed? Don't we instead want to say:

```cs
    public NativeFunction function = new NativeFunction((values) =>
```
Or is this some form of [lazy initialization](https://docs.microsoft.com/en-us/dotnet/framework/performance/lazy-initialization)?

2020-12-14 00:57 UTC, merged