Document VA implicit variables `$=` and `$-`
EDCD/EDDI pull request #2027
Opened 2020-11-29 22:49 UTC by Tkael

Revise `$-` output to more clearly render commander phonetic name.
Resolves #2026.

2020-11-30 02:33 UTC, richardbuckle requested changes
Suggest "stands for" instead of "shall be replaced with" here and below.

2020-11-30 02:59 UTC, Tkael commented
I'm not sure I understand the reasoning. Why prefer "stands for"?

2020-11-30 23:30 UTC, richardbuckle commented
I just feel that "shall be replaced with" comes across as maybe a bit too formal and stitled.

2020-12-08 21:08 UTC, richardbuckle approved these changes

2020-12-09 00:45 UTC, merged